[project]
name = "integrado"
version = "0.1.0"
description = "integrado using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.203.1,<1.0.0",
    "fastapi",
    "uvicorn",
    "python-dotenv",
    "requests",
    "pydantic",
    "google-api-python-client",
    "pymongo"
]

[project.scripts]
integrado = "integrado.main:run"
run_crew = "integrado.main:run"
train = "integrado.main:train"
replay = "integrado.main:replay"
test = "integrado.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
